### ISSUE TITLE
Multicloud deployment fails to load iptable information set on nodes

### ISSUE THREAD

**Issue by suslmk-lee** [K-PaaS/container-platform#5]
Multicloud deployment fails to load iptable information set on nodes

It happens on reboot and needs to be fixed.

**Comment by jinhyojin** [comment]
This issue has been fixed and applied to container platform v1.5.1.

For more information, please refer to [Modify iptables save task](https://github.com/K-PaaS/cp-deployment/commit/e45892a5e66f5011d8b0eb5ebe4a32bb078486d8).

**Comment by suslmk-lee** [comment]
The feature has been improved, so closing this issue.

If you encounter any further problems, please feel free to reopen it or create a new issue.
