### ISSUE TITLE
reboot cluster??

### ISSUE THREAD

**Issue by mctlmk1** [K-PaaS/container-platform#6]
I have a cluster setup and portal installed, but when I unload and restart the server, I can't access the portal. 
Is there something I need to configure?

**Comment by hoon77** [comment]
**클러스터 노드 재구동 후 포털 접속 시  '해당 클러스터 API 서버와 통신 할 수 없습니다'  메시지 발생** 

Vault 파드가 Seal 상태로 의심됩니다. 
Vault 파드가 재시작 되거나 클러스터 노드 VM이 재구동 되면 Vault가 Seal 상태(잠김상태)가 되며, Unseal 상태로 하기 위해서는 Unseal Key가 필요합니다.

​Vault Unseal Key는 아래 경로에 위치합니다.
경로 : ~/workspace/container-platform/cp-portal-deployment/vault/cp-vault-unseal-key

​노드VM 재구동 후 Vault UI에 접속하시어 keys 또는 keys_base64 중 2개의 키 입력하여 Unseal 상태로 해제 바랍니다.

​

**Comment by suslmk-lee** [comment]
이 문제가 해결되었으므로 이 이슈를 클로즈합니다.

추가적인 문제가 있으면 언제든지 다시 열어주세요.
