### ISSUE TITLE
클러스터 생성 시 발급한 SSH 키를 Portal 설치 시 Overwrite

### ISSUE THREAD

**Issue by ygm0516** [K-PaaS/container-platform#8]
클러스터 생성 시 발급한 SSH 키를 Portal 설치 시 Overwrite하여 HostCluster관련 reset 등 이후 작업 처리 안됨

**Comment by jinhyojin** [comment]
해당 이슈사항은 수정되어 컨테니어 플랫폼 v1.5.1.1 에 적용되었습니다. 

자세한 내용은 [Modify Terraman Script, Edge Mosquitto Config](https://github.com/K-PaaS/cp-deployment/commit/4ed3f5834e34683ac7db5d8cba6df02695dc18e2) 를 참고해 주시기 바랍니다.

**Comment by suslmk-lee** [comment]
해당 기능이 개선되었으므로 이 이슈를 클로즈 합니다.

추가적인 문제가 있으면 언제든 다시 이슈를 열어주세요.
