### ISSUE TITLE
멀티클러스터 환경 cp portal stresschaos metric을 mariadb에 저장할 때 데이터 중복 이슈

### ISSUE THREAD

**Issue by dancingcarrot** [K-PaaS/container-platform#9]
상황 재현 : 멀티클러스터 환경에서 cp portal 을 통해 동일한 이름의 stresschaos 생성

**Comment by jinhyojin** [comment]
해당 이슈는 Host 클러스터에서만 동작하도록 변경되어 처리되었습니다. 

K-PaaS 컨테이너 플랫폼 v1.6.0 부터 Portal-ui에 chaos 기능이 추가되었으며,

사용방법은 [chaos 사용가이드](https://github.com/K-PaaS/container-platform/blob/master/use-guide/portal/cp-portal-use-guide-chaos.md) 를 참고해 주시기 바랍니다.

**Comment by suslmk-lee** [comment]
해당 기능이 개선되었으므로 이 이슈를 클로즈합니다.

추가적인 문제가 있으면 언제든지 다시 열어주세요.
